version: '3'

services:
  bot:
    image: dimitrysukalo/erokytne:0.0.3
    container_name: erokytne-bot
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_APPL_PATH: "/erokytne"
      General:AutoMigrations: "true"
    ports:
      - "5004:80"